=== csgf/application-registry-portlet/web/conf/chart-config.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/config.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE charts SYSTEM "config.dtd">

    <charts>
    ...
    </charts>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT charts (chart)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT chart (query|title)*>
<!ATTLIST chart
    name CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT title (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT query (where|group|from|select)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT select (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT from (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT group (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT where (#PCDATA)>

=== csgf/application-registry-portlet/web/conf/chart-config.xml
<?xml version="1.0"?>
<!DOCTYPE data SYSTEM "chart-config.dtd">
<charts>
    <chart name="status">
    <title>Status distribution</title>
       <query>
            <select>Count(*) as value, concat(statusName,'') as name</select>
            <from/>
            <where/>
            <group>name</group>
            </query>
    </chart>

    <chart name="domain">
    <title>Domain distribution</title>
        <query>
            <select>Count(*) as value, concat(domain,'') as name</select>
            <from/>
            <where/>
            <group>name</group>
        </query>
    </chart>

    <chart name="vo">
    <title>VO distribution</title>
        <query>
            <select>Count(*) as value, concat(VO,'') as name</select>
            <from/>
            <where/>
            <group>name</group>
        </query>
    </chart>
    <chart name="country">

    <title>Country distribution</title>
        <query>
            <select>Count(*) as value, concat(country,'') as name</select>
            <from/>
            <where/>
            <group>name</group>
        </query>
    </chart>

       
</charts>
